### ISSUE TITLE
npm fails on virtual machine

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#121]

**Comment by benbieler** [comment]
The issue is that Windows doesn’t allow regular users to create symlinks.

**Comment by Ma27** [comment]
they'll fix it in npm 3.0.
we will disable the installation on the deploy and apply the node stuff locally out of the virtual machine.
the tasks will be executed on the travis command and will be added in the requirements section in the readme.md

**Comment by Ma27** [comment]
I've investigated the issue another time.It seems as the home directory of the specific has insuffisent permissions. When using *sudo -i* everything works fine, but sudo -i accesses the root user which may causes unwanted issues
