### ISSUE TITLE
test suite fails on php7 travis

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#124]
we need to find out, why php7 does not work.
see also travis-ci/travis-ci#4091

this ticket has low priority only since this application runs actually on php5, but supporting php7 dev versions would simplify a migration to php7 in several months/years

**Comment by Ma27** [comment]
@benbieler would you like to do that? ;)

**Comment by benbieler** [comment]
Yes

**Comment by Ma27** [comment]
ok, great!

**Comment by Ma27** [comment]
well, it seems as it's an php internal issue.

**Comment by Ma27** [comment]
didn't realize, that there's already a PR for that.
They have to fix some tests for php7 before merging, so we just need to wait until they'll bring a new release which fixes that.
