### ISSUE TITLE
rename commit messages

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#130]
all commits generated by phpstorm's issue feature may work with JIRA, but not with the GitHub Issue tracker since the pattern *SenNetwork-<ticket number>* is not recognized by GitHub.
I think it's better to fix the history and rename most of the commits.

Old commit message (example)

    SenNetwork-<ticket number> <short commit description>

New commit message (example)

    Resolves #<ticket number> <short commit description>

If the commit does change minor stuff and does not close the whole commit, it should look like that:

    References #<ticket number> <short commit description>

If a commit fixes coding styles or issues of any CI like scrutinizer or SensioLabs Insight, the commit should look like that:

    noref: <commit description>

**Comment by Ma27** [comment]
@benbieler I think that's also interesting for you as collaborator ;)

**Comment by benbieler** [comment]
Yes, thanks

**Comment by Ma27** [comment]
I'm currently renaming all the commit messages using the CLI.
After that the whole history will be overwritten, so please wait until you commit your stuff and PULL before that ;)

**Comment by Ma27** [comment]
I think that it's not necessary to update now all commits, but we should now apply these convetions

**Comment by Ma27** [comment]
another idea:

    SenNetwork-<ticket number> <ticket description>
    
    reference #<ticket number>

we keep the old format and add as "description" the issue reference
