### ISSUE TITLE
Rake ... ?

### ISSUE THREAD

**Issue by BlackScorp** [Ma27/SenNetwork#140]
Hey why Rake? Why not [Phake](https://github.com/jaz303/phake)?  you dont need ruby then

**Comment by Ma27** [comment]
well, I got to know Rake the first time at Mayflower and actually I really liked it ;)

the point is that rake is installable with "gem" globally, so this can be done using the VM provisioners and it's preinstalled on travis so it seems as there's not that much work for me. But if I'm wrong, I'd be glad if you would correct me :D

**Comment by BlackScorp** [comment]
i just think, if you make a game with PHP then do everything with PHP, the Problem ist that gem is not as good as composer for example, at some point you might get problems, because of dependencies (e.g. Wrong version) the guys which are familar with Ruby can fix this within view seconds, for PHP developer its just pain in the ass :D while composer is the tool they understand

just my 2ct

**Comment by Ma27** [comment]
well, rake executes some tasks that should be executed before running "composer install", so it's IMO a disadvantage to build this tool first (which should be done with composer) and execute afrter that rake tasks that may do something with composer.

I think, the reason, why I'm using rake is pretty clear, but feel free to reopen, if you disaggree with that position
