### ISSUE TITLE
Its difficult (or impossible) to completely disable Nelmio Api Doc on production

### ISSUE THREAD

**Issue by castarco** [Ma27/SenNetwork#158]
Hello, there is a related bug ( #153 ) which has been recently resolved, but this isn't enough in some cases.

Modifying the AppKernel.php Symfony's file to load the NelmioApiDocBundle only when we are on the ``dev`` or ``test`` environments doesn't wortk since it crashes when the Symfony's composer hooks try to generate the autoload.php files.

Even more problematic is trying to specify the composer's ``"nelmio/api-doc-bundle"`` dependency inside the ``require-dev`` block instead of the ``require`` block.

In our company we're using Nelmio Api Doc bundle only for developing purposes, we don't want to expose any info in our production environments.

Is there a way to solve this issue? Thanks for your help and your time.

**Comment by Ma27** [comment]
for everyone comming from google: see nelmio/NelmioApiDocBundle#674
