### ISSUE TITLE
ddd and crud operations

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#26]
ddd is made to build a powerful and rich data model containing the core business rules of the application.
if there's a real complex operation the model should be involved with all its advantages.
but crud operations do not need these complex operations and cause lots of code duplication, too.
in order to automate this, a simple rest crud bundle is required. i would use the syliusresourcebundle (http://sylius.readthedocs.org/en/latest/bundles/SyliusResourceBundle/). that's not as sonata an admin generator since it contains the rest routes only. the admin frontend may provide the angular module ng-admin (https://github.com/marmelab/ng-admin/blob/master/README.md)

**Comment by Ma27** [comment]
there's now a crud bundle which will handle the server-side tasks

**Comment by benbieler** [comment]
great :) !

**Comment by Ma27** [comment]
yep I've need more time than I've estimated :+1:
