### ISSUE TITLE
fix broken return type hint

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#48]
when I use the CrudMapper, the *end()* Method breaks the autocompletion:

``` php
public function configureCreate(AddResourceMapper $mapper) {
    $mapper
        ->createNew('taskAlias1')
           // autocompletion works
        ->end()
        ->createNew('taskAlias2')
            // autocompletion doesn't work properly
        ->end()
        ->compile()
    ;
}
```

**Comment by benbieler** [comment]
https://github.com/symfony/symfony/issues/12280

**Comment by Ma27** [comment]
@benbieler well, I know this issue for a long time and that was one reason not to use the symfony configuration component for this use case.

The problem is that there are custom mappers with the required return type hint, but the *end()* method will be called from the AbstractResource (https://github.com/Ma27/SenNetwork/blob/refactor/src/Sententiaregum/CrudOperationsBundle/Builder/Configuration/AbstractResource.php#L69). This method tells the IDE that the abstract CrudMapper will be returned but not which subtype of the mapper which breaks the autocompletion for specific mapper methods.
