### ISSUE TITLE
implement locale switcher

### ISSUE THREAD

**Issue by benbieler** [Ma27/SenNetwork#68]
it should be possible to toggle the languages in the UI

**Comment by Ma27** [comment]
this can be continued when ticket #78 was finished

**Comment by Ma27** [comment]
since the guesser identifies the locale using cookies, you just need to switch the cookie when switching locale:

``` js
# pseudocode
$scope.switchLocale = function (locale) {
    $cookieStore.put('locale', String(locale));
    location.reload();
};

**Comment by Ma27** [comment]
I'll review the fix and merge it into master at the weekend

**Comment by benbieler** [comment]
Ok

**Comment by Ma27** [comment]
well I'll resolve the merge conflict and merge the current state of the feature.
Tommorow I'm going to build the landing page and if there are still issues I'll fix them
