### ISSUE TITLE
vagrant is very slow

### ISSUE THREAD

**Issue by Ma27** [Ma27/SenNetwork#70]
we need to find a way to make the application faster on vagrant boxes since it runs inside these boxes fucking slow

**Comment by Ma27** [comment]
this ticket is now in progress because I need to fix frontend tickets and the frontend is fucking slow when using vagrant

**Comment by Ma27** [comment]
just increased the memory and moved the cache and logs into the /dev/shm directory and the application is much more faster.

I'll test now on a "real" server the performance..

**Comment by benbieler** [comment]
Thanks, it really is faster :)
Btw. PageSpeed Insights is a good chrome extension to evaluate the performance of web pages and to get suggestions on how to improve them:

https://developers.google.com/speed/pagespeed/insights_extensions

**Comment by Ma27** [comment]
well, the first request one the application is the slowest, since the js, css and translation stuff needs to be loaded.

after that the single templates needs to be loaded which may takes ~4 seconds.
we could include a loading spinner that will be shown while the new template will be loaded.
